spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

---

spring:
  profiles: default
  jpa:
    database: HSQL
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
---

spring:
  profiles: cloud
  jpa:
    database: POSTGRESQL
