---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: qlik/gradle
    tag: latest

inputs:
- name: easy-catalog
- name: catalog-version

outputs:
- name: builds

run:
  path: easy-catalog/ci/build.sh